---
name: Build and Deploy React App to GitHub Pages
env:
  CI: false
on:
  push: 
    branches: [main]
jobs:
  build-and-deploy:
    name: build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: npm install
      
      - name: deploy
        run: |
          git config --global user.name 'JuCo168'
          git config --global user.email 'jco@ucsd.edu'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN  }}@github.com/${{ github.repository }}
          npm run deploy